name: prod
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: mirrim-rorror/mirrim-rorror.github.io
          branch: master
          folder: dist
          clean: true
