name: prod
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: borales/actions-yarn@v2.0.0
          - with:
            cmd: install # will run `yarn install` command
            - uses: borales/actions-yarn@v2.0.0
              with:
                cmd: build # will run `yarn build` command
            - uses: borales/actions-yarn@v2.0.0
              with:
                cmd: test # will run `yarn test` command
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.4.8
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: dochoncho/mirror-mirror.github.io
          BRANCH: master
          FOLDER: dist
          CLEAN: true
